---
before_install:
  - sudo apt-get install -qq augeas-tools augeas-lenses libaugeas-dev
language: ruby
script: "bundle exec rake rspec"
rvm:
  - 1.9.3
  - 2.0.0
notifications:
  email:
    - stephen@bitbin.de
env:
  - PUPPET_VERSION="~> 2.7.0" 
  - PUPPET_VERSION="~> 3.0"
